### ISSUE TITLE
Too many potholes generated

### ISSUE THREAD

**Issue by OcrSu** [ToCraft/CraftedTerrainGeneration#1]
### Describe your idea, include images if necessary

![image](https://github.com/user-attachments/assets/4021eea4-d965-457a-913d-c626f424b46e)
There are too many potholes generated.
How to reduce its generation probability or turn off generation.
I am using an example data pack

**Comment by ToCraft** [comment]
You have to modify the "carver" field in the generator settings.  You'll have to raise the carver threshold. Take a look at the [wiki](https://github.com/ToCraft/CraftedTerrainGeneration/wiki/Starting-with-Data-Packs) for detail.
